### ISSUE TITLE
Problems about params_proto

### ISSUE THREAD

**Issue by weakenleg2** [zbzhu99/madiff#1]
Hi,

When I try to run python run_experiment.py -e exp_specs/mpe/mad_mpe_tag_ctde_exp.yaml
I met some problems about my_logger:
Traceback (most recent call last):
  File "/home/guo/anaconda3/envs/madiff/lib/python3.8/site-packages/params_proto/neo_proto.py", line 168, in __getattribute__
    value = get_hooks[-1](self, item)
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_scripts/train.py", line 324, in <module>
    main(Config, RUN)
  File "run_scripts/train.py", line 73, in main
    decentralized_execution=Config.decentralized_execution,
  File "/home/guo/anaconda3/envs/madiff/lib/python3.8/site-packages/params_proto/neo_proto.py", line 171, in __getattribute__
    value = type.__getattribute__(self, item)
AttributeError: type object 'Config' has no attribute 'decentralized_execution'
I think my env version about this library is the same with requirement.txt, can I get some help?
Many thanks!

Below is my current env:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
aiofile                   3.8.8                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
argcomplete               3.2.2                    pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
atomicwrites              1.4.1                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
black                     23.1.0                   pypi_0    pypi
boto3                     1.34.31                  pypi_0    pypi
botocore                  1.34.31                  pypi_0    pypi
bracex                    2.4                      pypi_0    pypi
ca-certificates           2023.12.12           h06a4308_0  
cachetools                4.2.4                    pypi_0    pypi
caio                      0.9.13                   pypi_0    pypi
certifi                   2023.11.17               pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               1.3.0                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
d4rl                      1.1                      pypi_0    pypi
ddpg-agent                0.0.1                     dev_0    <develop>
deepdiff                  6.7.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
dm-control                1.0.8                    pypi_0    pypi
dm-env                    1.6                      pypi_0    pypi
dm-tree                   0.1.8                    pypi_0    pypi
einops                    0.7.0                    pypi_0    pypi
enum34                    1.1.10                   pypi_0    pypi
expandvars                0.12.0                   pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
fonttools                 4.47.2                   pypi_0    pypi
functional-notations      0.5.2                    pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.9                    pypi_0    pypi
glfw                      1.12.0                   pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.60.0                   pypi_0    pypi
gtimer                    1.0.0b5                  pypi_0    pypi
gym                       0.23.1                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
gymnasium                 0.27.1                   pypi_0    pypi
gymnasium-notices         0.0.1                    pypi_0    pypi
h5py                      3.10.0                   pypi_0    pypi
html5tagger               1.3.0                    pypi_0    pypi
httptools                 0.6.1                    pypi_0    pypi
idna                      3.6                      pypi_0    pypi
imageio                   2.33.1                   pypi_0    pypi
imageio-ffmpeg            0.4.9                    pypi_0    pypi
importlib-metadata        7.0.1                    pypi_0    pypi
isort                     5.12.0                   pypi_0    pypi
jax-jumpy                 1.0.0                    pypi_0    pypi
jaynes                    0.8.11                   pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    0.16.0                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
labmaze                   1.0.6                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lxml                      5.1.0                    pypi_0    pypi
madiff                    0.0.0                     dev_0    <develop>
mamujoco                  0.0.0                     dev_0    <develop>
markdown                  3.5.2                    pypi_0    pypi
markupsafe                2.1.4                    pypi_0    pypi
matplotlib                3.6.3                    pypi_0    pypi
mjrl                      1.0.0                    pypi_0    pypi
ml-logger                 0.8.69                   pypi_0    pypi
mock                      5.1.0                    pypi_0    pypi
more-itertools            10.2.0                   pypi_0    pypi
mpyq                      0.2.5                    pypi_0    pypi
mujoco                    2.3.0                    pypi_0    pypi
mujoco-py                 2.1.2.14                 pypi_0    pypi
multiagent                0.0.1                     dev_0    <develop>
multidict                 6.0.4                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1                      pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
numpy-stl                 2.17.1                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
openssl                   3.0.12               h7f8727e_0  
opt-einsum                3.1.0                    pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
packaging                 23.0                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
params-proto              2.9.6                    pypi_0    pypi
path                      15.0.0                   pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.1           py38h06a4308_0  
platformdirs              4.1.0                    pypi_0    pypi
pluggy                    1.4.0                    pypi_0    pypi
portpicker                1.6.0                    pypi_0    pypi
protobuf                  4.25.2                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pybullet                  3.2.6                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pycurl                    7.45.2                   pypi_0    pypi
pygame                    2.5.2                    pypi_0    pypi
pyglet                    1.5.0                    pypi_0    pypi
pyopengl                  3.1.5                    pypi_0    pypi
pyparsing                 2.2.2                    pypi_0    pypi
pyrsistent                0.16.0                   pypi_0    pypi
pysc2                     3.0.0                    pypi_0    pypi
pytest                    3.8.2                    pypi_0    pypi
python                    3.8.18               h955ad1f_0  
python-dateutil           2.7.3                    pypi_0    pypi
python-utils              2.4.0                    pypi_0    pypi
pytz                      2023.4                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
requests-futures          1.0.1                    pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
requests-toolbelt         1.0.0                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.18.5                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
s2clientprotocol          5.0.12.91115.0           pypi_0    pypi
s2protocol                5.0.12.91115.0           pypi_0    pypi
s3transfer                0.10.0                   pypi_0    pypi
sanic                     23.12.1                  pypi_0    pypi
sanic-cors                2.2.0                    pypi_0    pypi
sanic-routing             23.12.0                  pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
setuptools                68.2.2           py38h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sk-video                  1.1.10                   pypi_0    pypi
smmap                     3.0.5                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
subprocess32              3.5.4                    pypi_0    pypi
tensorboard               2.0.2                    pypi_0    pypi
tensorboardx              2.0                      pypi_0    pypi
tensorflow-estimator      2.0.0                    pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
torch                     1.12.1+cu113             pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
tracerite                 1.1.1                    pypi_0    pypi
typed-argument-parser     1.7.2                    pypi_0    pypi
typing                    3.7.4.3                  pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
ujson                     5.9.0                    pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
uvloop                    0.19.0                   pypi_0    pypi
waterbear                 2.6.8                    pypi_0    pypi
wcmatch                   8.5                      pypi_0    pypi
websocket-client          1.7.0                    pypi_0    pypi
websockets                12.0                     pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2           py38h06a4308_0  
whichcraft                0.6.1                    pypi_0    pypi
xz                        5.4.5                h5eee18b_0  
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Comment by zbzhu99** [comment]
Thank you for your interest in this repo! This is due to some legacy YAML files which are not compatible with current training code. I will double-check and update all YAML files this week.

**Comment by zbzhu99** [comment]
I have refactored `sequence.py`, `diffuser/models/diffusion.py`, and updated the YAML files in `exp_specs/`. You can try running the same experiment with the new config file, such as

```terminal
python run_experiment.py -e exp_specs/mpe/tag/mad_mpe_tag_ctde_exp.yaml
```

*Happy Lunar New Year!*
