### ISSUE TITLE
Issue with the SMAC 8m Dataset Format

### ISSUE THREAD

**Issue by Guowei-Zou** [zbzhu99/madiff#6]
Dear Mr. Zhu,

I apologize for bothering you again. I have encountered a new issue with the datasets you uploaded on September 20, 2024. The format of the **_smac\8m_** dataset is different from the other datasets, which causes an error when converting the dataset to the .npy format. Could you kindly update this dataset again?

Thank you very much for your assistance.

Best regards,

Guowei Zou
Sun Yat-sen University

![Picture1](https://github.com/user-attachments/assets/027ecf29-9c35-44fb-a978-28dd37d71f8e)

**Comment by zbzhu99** [comment]
I have updated the download link for 8m. Please try again.

**Comment by Guowei-Zou** [comment]
Thank you so much! I can download **_smac/8m_** now.
