### ISSUE TITLE
problem from the version of mujoco & mujoco_py

### ISSUE THREAD

**Issue by yycloudywind** [zbzhu99/madiff#7]
Dear Dr. Zhu,

I have encountered the following error:

error: passing argument 1 of '__pyx_f_9mujoco_py_4cymj_WrapMjVisual_global_' from incompatible pointer type [-Wincompatible-pointer-types]

It appears that there is a mismatch between the versions of mujoco_py and the Mujoco engine, even though both versions were installed according to your requirements: Mujoco-2.3.0 and mujoco_py 2.1.2.14. I am quite puzzled by this issue and would appreciate your guidance. Thank you in advance!

**Comment by zbzhu99** [comment]
I don’t think this issue is *entirely* due to a version mismatch. I checked both versions in my workspace—Mujoco 2.3.0 and mujoco_py 2.1.2.14—and they work without any issues. 

Could you provide more details on the error and your environment?

**Comment by yycloudywind** [comment]
Thank you for your reply! I have identified the cause of the issue, which was mainly due to not having sudo access when running the code on the server. This resulted in some environments requiring manual compilation, and issues during that process caused the previous errors. 

Actually, after resolving the above errors, I encountered new issues related to environment incompatibility. I tried running the following code: `python run_experiment.py -e exp_specs/mpe/spread/mad_mpe_spread_attn_exp.yaml`, but I encountered an error from mamujoco:

```
[ diffuser/environments/registration ] WARNING: not registering diffuser environments
pybullet build time: Nov 28 2023 23:51:11
~/anaconda3/envs/madiff2/lib/python3.8/site-packages/multiagent_mujoco/__init__.py:9: UserWarning: This code base is no longer maintained, and is not expected to be maintained again in the future.
For updated and maintained versions of these environments, please refer to Gymnasium Robotics (see https://robotics.farama.org/).
This maintained version includes documentation, support for the PettingZoo APi, current versions of Python, various bug fixes, and other quality of life improvements.
We encourage researchers to switch to the maintained version for all purposes other than comparing to results ran on this version of the environments.

  warnings.warn("This code base is no longer maintained, and is not expected to be maintained again in the future. \n"
Please read the raised warning, then press Enter to continue... (to suppress this prompt, please set the environment variable `SUPPRESS_GR_PROMPT=1`)
```

**Comment by zbzhu99** [comment]
Did you install the local version of multi-agent mujoco located in `./third_party/multiagent_mujoco` or did you install some other versions?

**Comment by dontlagother** [comment]
Dear Dr. Zhu,
when i transform the original dataset, i have encountered the following error:
Traceback (most recent call last):
  File "scripts\transform_og_marl_dataset.py", line 226, in <module>
    main(args.env_name, args.map_name, args.quality)
  File "scripts\transform_og_marl_dataset.py", line 37, in main
    filenames = sorted(filenames, key=get_fname_idx)
  File "scripts\transform_og_marl_dataset.py", line 26, in get_fname_idx
    dir_idx = sub_dir_to_idx[file_name.split("/")[-2]] * 1000
IndexError: list index out of range
can you give some suggestions about how to solve it or provide transformed data file<.npy>(smac)? Hope to your reply. Thank you in advance!
